// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ExtensionPopup.tsx": () => import("../components/mockups/ExtensionPopup.tsx"),
  "./components/mockups/MasterScanView.tsx": () => import("../components/mockups/MasterScanView.tsx"),
  "./components/mockups/TruthLayerView.tsx": () => import("../components/mockups/TruthLayerView.tsx")
};
